package model;

import javafx.beans.property.SimpleStringProperty;
import javafx.beans.value.ObservableValue;

/**
 * The GameResult is mapped with GameResult table in DB.
 * 
 * @author Jiaxiang Shan on 02/09/2020.
 */

public final class GameResult {
	
	/**
	 * id of the game result.
	 */
	private Integer gameResultID;
	
	/**
	 * name of the player.
	 */
	private String username;
	
	/**
	 * score of the player.
	 */
	private Integer score;
	
	/** ==============Constructors============== */
	
	/**
	 * Default constructor.
	 */
	
	public GameResult() {
		super();
	}
	
	/**
	 * Constructor with attributes except ingredientID -- for insertions;
	 * 
	 * @param userName
	 *            userName of the player of the game.
	 * 
	 * @param score
	 *            score of the player of the game.
	 * 
	 */
	
	public GameResult(String username, Integer score) {
		this(null, username, score);
	}

	/**
	 * Constructor of all attributes. -- Do not set gameResultID , it is
	 * auto-generated by database.
	 * 
	 * @param gameResultID
	 *            ID of the game.
	 * 
	 * @param userName
	 *            userName of the player of the game.
	 * 
	 * @param score
	 *            score of the player of the game.
	 * 
	 */
	 public GameResult(Integer gameResultID, String username, Integer score) {
		super();
		this.username = username;
		this.score = score;
	}
	 
	 /** ==============Getters and setters.============== */
	 /**
	  * @return the gameResultID
	  */
	public Integer getGameResultID() {
			return gameResultID;
		}
	 
	 /**
	  * @param gameResultID
	  *        the gameResultID to set
	  */
	public void setGameResultID(Integer gameResultID) {
			this.gameResultID = gameResultID;
		}
		
	/**
	  * @return the username
	  */
	public String getUserName() {
			return username;
		}
	 
	 /**
	  * @param username
	  *        the username to set
	  */
	public void setUserName(String userName) {
			this.username = userName;
		}
	
	 /**
	  * @return the score
	  */
	public Integer getScore() {
			return score;
		}
	 
	 /**
	  * @param score
	  *        the score to set
	  */
	public void setScore(Integer score) {
			this.score = score;
		}	
	
	/**
	 * @return the StringProperityUserName.
	 */
	public ObservableValue<String> getStringProperityUserName() {
		ObservableValue<String> obsString = new SimpleStringProperty(this.username);
		return obsString;
	}
	
	/**
	 * Override toString method, print basic information of a game result.
	 */
	@Override
	public String toString() {
		return "GameResult [gameResultID=" + gameResultID + ", username=" + username + ", score=" + score + "]";
	}
	 
}
